# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzKJey_X8_hraixE1yZtDUKDj2Uejwd1
"""

import torch

print("PyTorch:", torch.__version__)
print("GPU:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("Tên GPU:", torch.cuda.get_device_name(0))
else:
    print("Không phát hiện GPU")

!pip install -U ultralytics

from ultralytics import YOLO

model = YOLO("yolo12n.pt")

# 1. Upload ảnh
from google.colab import files

uploaded = files.upload()
image_name = next(iter(uploaded))

print("Ảnh đã tải lên:", image_name)


# 2. Chạy suy luận
results = model.predict(
    source=image_name,
    save=True
)


# 3. Hiển thị kết quả
from IPython.display import display
from PIL import Image

result_image = results[0].plot()

display(Image.fromarray(result_image[..., ::-1]))


# 4. Thông tin kết quả
print("Thư mục lưu kết quả:", results[0].save_dir)

# 1. Upload ảnh
from google.colab import files

uploaded = files.upload()
image_name = next(iter(uploaded))

print("Ảnh đã tải lên:", image_name)


# 2. Chạy suy luận
results = model.predict(
    source=image_name,
    save=True
)


# 3. Hiển thị kết quả
from IPython.display import display
from PIL import Image

result_image = results[0].plot()

display(Image.fromarray(result_image[..., ::-1]))


# 4. Thông tin kết quả
print("Thư mục lưu kết quả:", results[0].save_dir)