# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzKJey_X8_hraixE1yZtDUKDj2Uejwd1
"""

import torch

print("PyTorch:", torch.__version__)
print("GPU:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("Tên GPU:", torch.cuda.get_device_name(0))
else:
    print("Không phát hiện GPU")

!pip install -U ultralytics

from ultralytics import YOLO

model = YOLO("yolo12n.pt")

# 1. Upload ảnh
from google.colab import files

uploaded = files.upload()
image_name = next(iter(uploaded))

print("Ảnh đã tải lên:", image_name)


# 2. Chạy suy luận
results = model.predict(
    source=image_name,
    save=True
)


# 3. Hiển thị kết quả
from IPython.display import display
from PIL import Image

result_image = results[0].plot()

display(Image.fromarray(result_image[..., ::-1]))


# 4. Thông tin kết quả
print("Thư mục lưu kết quả:", results[0].save_dir)

# 1. Upload ảnh
from google.colab import files

uploaded = files.upload()
image_name = next(iter(uploaded))

print("Ảnh đã tải lên:", image_name)


# 2. Chạy suy luận
results = model.predict(
    source=image_name,
    save=True
)


# 3. Hiển thị kết quả
from IPython.display import display
from PIL import Image

result_image = results[0].plot()

display(Image.fromarray(result_image[..., ::-1]))


# 4. Thông tin kết quả
print("Thư mục lưu kết quả:", results[0].save_dir)

!nvidia-smi

!pip install -U ultralytics

import ultralytics

print("Ultralytics:", ultralytics.__version__)

from google.colab import files

uploaded = files.upload()

import zipfile
import os

zip_path = "Waste_Detection_v3_CLEAN_YOLO.zip"
extract_path = "/content/dataset"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("Đã giải nén dataset!")

import os

for root, dirs, files in os.walk("/content/dataset"):
    level = root.replace("/content/dataset", "").count(os.sep)

    if level <= 2:
        print("  " * level + os.path.basename(root) + "/")

import os
import yaml

dataset_path = "/content/dataset/Waste_Detection_v3_CLEAN_YOLO"

print("Các file trong dataset:")
print(os.listdir(dataset_path))

yaml_path = os.path.join(dataset_path, "data.yaml")

with open(yaml_path, "r") as f:
    data = yaml.safe_load(f)

print("\nNội dung data.yaml:")
print(data)

import os

for split in ["train", "valid", "test"]:
    image_path = os.path.join(dataset_path, split, "images")
    label_path = os.path.join(dataset_path, split, "labels")

    images = [
        f for f in os.listdir(image_path)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    labels = [
        f for f in os.listdir(label_path)
        if f.endswith(".txt")
    ]

    print(f"{split}:")
    print(f"  Ảnh   : {len(images)}")
    print(f"  Label : {len(labels)}")

from collections import Counter
import os

class_names = ["cardboard", "metal", "paper", "plastic", "trash"]

for split in ["train", "valid", "test"]:
    label_path = os.path.join(dataset_path, split, "labels")
    counter = Counter()

    for file in os.listdir(label_path):
        if file.endswith(".txt"):
            with open(os.path.join(label_path, file), "r") as f:
                for line in f:
                    parts = line.strip().split()

                    if parts:
                        class_id = int(parts[0])
                        counter[class_id] += 1

    print(f"\n{split.upper()}")
    for i, name in enumerate(class_names):
        print(f"{name}: {counter[i]}")

from ultralytics import YOLO

# ==============================
# 1. Đường dẫn dataset
# ==============================
data_path = "/content/dataset/Waste_Detection_v3_CLEAN_YOLO/data.yaml"

# ==============================
# 2. Khởi tạo YOLO12n pretrained
# ==============================
model = YOLO("yolo12n.pt")

# ==============================
# 3. Huấn luyện thử
# ==============================
results = model.train(
    data=data_path,

    # Cấu hình chính
    imgsz=640,
    batch=16,
    epochs=50,

    # GPU
    device=0,

    # Augmentation mức vừa phải
    degrees=10,
    translate=0.1,
    scale=0.5,
    fliplr=0.5,
    mosaic=0.5,
    mixup=0.0,

    # Lưu checkpoint
    save=True,
    save_period=10,

    # Thư mục kết quả
    project="/content/runs/yolo12n_week3",
    name="train",

    # Hiển thị thông tin
    verbose=True
)

print("\n==============================")
print("HUẤN LUYỆN HOÀN TẤT")
print("==============================")
print("Kết quả được lưu tại:")
print("/content/runs/yolo12n_week3/train")
print("\nBest model:")
print("/content/runs/yolo12n_week3/train/weights/best.pt")
print("\nLast model:")
print("/content/runs/yolo12n_week3/train/weights/last.pt")

!pip install -q ultralytics

import ultralytics

print("Ultralytics:", ultralytics.__version__)

from ultralytics import YOLO

# ==============================
# 1. Đường dẫn dataset
# ==============================
data_path = "/content/dataset/Waste_Detection_v3_CLEAN_YOLO/data.yaml"

# ==============================
# 2. Khởi tạo YOLO12n pretrained
# ==============================
model = YOLO("yolo12n.pt")

# ==============================
# 3. Huấn luyện thử
# ==============================
results = model.train(
    data=data_path,

    # Cấu hình chính
    imgsz=640,
    batch=16,
    epochs=50,

    # GPU
    device=0,

    # Augmentation mức vừa phải
    degrees=10,
    translate=0.1,
    scale=0.5,
    fliplr=0.5,
    mosaic=0.5,
    mixup=0.0,

    # Lưu checkpoint
    save=True,
    save_period=10,

    # Thư mục kết quả
    project="/content/runs/yolo12n_week3",
    name="train",

    # Hiển thị thông tin
    verbose=True
)

print("\n==============================")
print("HUẤN LUYỆN HOÀN TẤT")
print("==============================")
print("Kết quả được lưu tại:")
print("/content/runs/yolo12n_week3/train")
print("\nBest model:")
print("/content/runs/yolo12n_week3/train/weights/best.pt")
print("\nLast model:")
print("/content/runs/yolo12n_week3/train/weights/last.pt")

from ultralytics import YOLO
import yaml
import os

# Đường dẫn dataset thật
dataset_path = "/content/dataset/Waste_Detection_v3_CLEAN_YOLO"

# Tạo cấu hình YOLO với đường dẫn tuyệt đối
data_config = {
    "train": f"{dataset_path}/train/images",
    "val": f"{dataset_path}/valid/images",
    "test": f"{dataset_path}/test/images",
    "nc": 5,
    "names": [
        "cardboard",
        "metal",
        "paper",
        "plastic",
        "trash"
    ]
}

# Lưu file cấu hình mới
new_yaml = "/content/waste_data.yaml"

with open(new_yaml, "w") as f:
    yaml.dump(data_config, f, sort_keys=False)

print("Đã tạo:", new_yaml)
print("\nNội dung:")
print(data_config)

# Kiểm tra các thư mục có tồn tại không
print("\nKiểm tra dataset:")
print("Train:", os.path.exists(f"{dataset_path}/train/images"))
print("Valid:", os.path.exists(f"{dataset_path}/valid/images"))
print("Test :", os.path.exists(f"{dataset_path}/test/images"))

model = YOLO("yolo12n.pt")

results = model.train(
    data="/content/waste_data.yaml",
    imgsz=640,
    batch=16,
    epochs=50,
    device=0,

    degrees=10,
    translate=0.1,
    scale=0.5,
    fliplr=0.5,
    mosaic=0.5,
    mixup=0.0,

    save=True,
    save_period=10,

    project="/content/runs/yolo12n_week3",
    name="train",
    verbose=True
)

from ultralytics import YOLO
from google.colab import files
from IPython.display import display
from PIL import Image
import os

# 1. Load mô hình tốt nhất sau khi training
model = YOLO("/content/runs/yolo12n_week3/train-2/weights/best.pt")

# 2. Tải ảnh rác muốn kiểm tra
uploaded = files.upload()

# 3. Lấy tên ảnh vừa tải
image_path = list(uploaded.keys())[0]

# 4. Chạy nhận diện
results = model.predict(
    source=image_path,
    conf=0.25,
    save=True
)

# 5. Hiển thị ảnh sau khi nhận diện
result_image = results[0].plot()
display(Image.fromarray(result_image[..., ::-1]))

# 6. Hiển thị thông tin kết quả
print("Ảnh đầu vào:", image_path)
print("Kết quả được lưu tại:", results[0].save_dir)

from ultralytics import YOLO
from google.colab import files
from IPython.display import display
from PIL import Image
import os

# 1. Load mô hình tốt nhất sau khi training
model = YOLO("/content/runs/yolo12n_week3/train-2/weights/best.pt")

# 2. Tải ảnh rác muốn kiểm tra
uploaded = files.upload()

# 3. Lấy tên ảnh vừa tải
image_path = list(uploaded.keys())[0]

# 4. Chạy nhận diện
results = model.predict(
    source=image_path,
    conf=0.25,
    save=True
)

# 5. Hiển thị ảnh sau khi nhận diện
result_image = results[0].plot()
display(Image.fromarray(result_image[..., ::-1]))

# 6. Hiển thị thông tin kết quả
print("Ảnh đầu vào:", image_path)
print("Kết quả được lưu tại:", results[0].save_dir)

from ultralytics import YOLO
from google.colab import files
from IPython.display import display
from PIL import Image

# Load mô hình đã train
model = YOLO("/content/runs/yolo12n_week3/train-2/weights/best.pt")

# Tải ảnh test
uploaded = files.upload()

for image_path in uploaded.keys():

    print("\n==============================")
    print("Ảnh:", image_path)

    # Hạ confidence xuống 0.05 để xem mô hình có dự đoán yếu hay không
    results = model.predict(
        source=image_path,
        conf=0.05,
        save=True
    )

    result = results[0]

    # In các đối tượng mô hình dự đoán
    if len(result.boxes) == 0:
        print("Không có dự đoán nào ngay cả ở conf = 0.05")
    else:
        print("Các dự đoán:")

        for box in result.boxes:
            cls_id = int(box.cls[0])
            conf = float(box.conf[0])
            name = model.names[cls_id]

            print(f"- {name}: {conf:.3f}")

    # Hiển thị ảnh kết quả
    result_image = result.plot()
    display(Image.fromarray(result_image[..., ::-1]))

from ultralytics import YOLO
from google.colab import files
from IPython.display import display
from PIL import Image

# Load mô hình đã train
model = YOLO("/content/runs/yolo12n_week3/train-2/weights/best.pt")

# Tải ảnh test
uploaded = files.upload()

for image_path in uploaded.keys():

    print("\n==============================")
    print("Ảnh:", image_path)

    # Hạ confidence xuống 0.05 để xem mô hình có dự đoán yếu hay không
    results = model.predict(
        source=image_path,
        conf=0.05,
        save=True
    )

    result = results[0]

    # In các đối tượng mô hình dự đoán
    if len(result.boxes) == 0:
        print("Không có dự đoán nào ngay cả ở conf = 0.05")
    else:
        print("Các dự đoán:")

        for box in result.boxes:
            cls_id = int(box.cls[0])
            conf = float(box.conf[0])
            name = model.names[cls_id]

            print(f"- {name}: {conf:.3f}")

    # Hiển thị ảnh kết quả
    result_image = result.plot()
    display(Image.fromarray(result_image[..., ::-1]))

from ultralytics import YOLO
from google.colab import files
from IPython.display import display
from PIL import Image

# Load mô hình đã train
model = YOLO("/content/runs/yolo12n_week3/train-2/weights/best.pt")

# Tải ảnh test
uploaded = files.upload()

for image_path in uploaded.keys():

    print("\n==============================")
    print("Ảnh:", image_path)

    # Hạ confidence xuống 0.05 để xem mô hình có dự đoán yếu hay không
    results = model.predict(
        source=image_path,
        conf=0.05,
        save=True
    )

    result = results[0]

    # In các đối tượng mô hình dự đoán
    if len(result.boxes) == 0:
        print("Không có dự đoán nào ngay cả ở conf = 0.05")
    else:
        print("Các dự đoán:")

        for box in result.boxes:
            cls_id = int(box.cls[0])
            conf = float(box.conf[0])
            name = model.names[cls_id]

            print(f"- {name}: {conf:.3f}")

    # Hiển thị ảnh kết quả
    result_image = result.plot()
    display(Image.fromarray(result_image[..., ::-1]))

import os
import random
from PIL import Image, ImageDraw

# ==============================
# 1. Đường dẫn dataset
# ==============================
dataset_path = "/content/dataset/Waste_Detection_v3_CLEAN_YOLO"

class_names = ["cardboard", "metal", "paper", "plastic", "trash"]

# Chọn tập dữ liệu muốn kiểm tra
split = "train"   # đổi thành "valid" hoặc "test" nếu muốn

image_dir = os.path.join(dataset_path, split, "images")
label_dir = os.path.join(dataset_path, split, "labels")

# ==============================
# 2. Chọn ngẫu nhiên một ảnh
# ==============================
image_files = [
    f for f in os.listdir(image_dir)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
]

image_file = random.choice(image_files)

image_path = os.path.join(image_dir, image_file)

# Tên label tương ứng
label_file = os.path.splitext(image_file)[0] + ".txt"
label_path = os.path.join(label_dir, label_file)

print("Ảnh được kiểm tra:", image_file)
print("Label tương ứng:", label_file)

# ==============================
# 3. Đọc ảnh
# ==============================
image = Image.open(image_path).convert("RGB")

width, height = image.size

# ==============================
# 4. Đọc label YOLO
# ==============================
labels = []

if os.path.exists(label_path):

    with open(label_path, "r") as f:
        lines = f.readlines()

    for line in lines:

        parts = line.strip().split()

        if len(parts) != 5:
            continue

        class_id = int(parts[0])
        x_center = float(parts[1])
        y_center = float(parts[2])
        box_width = float(parts[3])
        box_height = float(parts[4])

        # Chuyển YOLO format -> tọa độ pixel
        x1 = int((x_center - box_width / 2) * width)
        y1 = int((y_center - box_height / 2) * height)

        x2 = int((x_center + box_width / 2) * width)
        y2 = int((y_center + box_height / 2) * height)

        class_name = class_names[class_id]

        labels.append((class_id, class_name, x1, y1, x2, y2))

else:
    print("Không tìm thấy file label!")

# ==============================
# 5. In class thực tế của dataset
# ==============================
print("\n===== LABEL CỦA DATASET =====")

if len(labels) == 0:
    print("Ảnh này không có label.")
else:
    for i, label in enumerate(labels, 1):
        class_id, class_name, x1, y1, x2, y2 = label

        print(f"Đối tượng {i}:")
        print(f"  Class ID   : {class_id}")
        print(f"  Class name : {class_name}")
        print(f"  Bounding Box: ({x1}, {y1}) -> ({x2}, {y2})")

# ==============================
# 6. Vẽ Bounding Box
# ==============================
draw = ImageDraw.Draw(image)

for class_id, class_name, x1, y1, x2, y2 in labels:

    draw.rectangle(
        [x1, y1, x2, y2],
        outline="red",
        width=3
    )

    draw.text(
        (x1, max(0, y1 - 20)),
        class_name,
        fill="red"
    )

# ==============================
# 7. Hiển thị ảnh
# ==============================
display(image)

from PIL import Image
import matplotlib.pyplot as plt
import os

# Đường dẫn ảnh và label
image_path = "/content/dataset/Waste_Detection_v3_CLEAN_YOLO/train/images/1789392493658_285425636973233444_5944122805105729455_ec74218c5c797a6b6681af748365bf62_jpg.rf.6170899c46cb549083b8add351aa69f0.jpg"

label_path = image_path.replace("/images/", "/labels/").rsplit(".", 1)[0] + ".txt"

# Đọc ảnh
img = Image.open(image_path)
print("Kích thước ảnh:", img.size)

# Hiển thị ảnh
plt.figure(figsize=(10, 8))
plt.imshow(img)
plt.axis("off")
plt.title("Ảnh trong dataset - kiểm tra label")
plt.show()

# Đọc label
print("\n===== LABEL =====")
with open(label_path, "r") as f:
    for line in f:
        print(line.strip())

from ultralytics import YOLO
from google.colab import files
from IPython.display import display
from PIL import Image

# Load mô hình đã train
model = YOLO("/content/runs/yolo12n_week3/train-2/weights/best.pt")

# Tải ảnh test
uploaded = files.upload()

for image_path in uploaded.keys():

    print("\n==============================")
    print("Ảnh:", image_path)

    # Hạ confidence xuống 0.05 để xem mô hình có dự đoán yếu hay không
    results = model.predict(
        source=image_path,
        conf=0.05,
        save=True
    )

    result = results[0]

    # In các đối tượng mô hình dự đoán
    if len(result.boxes) == 0:
        print("Không có dự đoán nào ngay cả ở conf = 0.05")
    else:
        print("Các dự đoán:")

        for box in result.boxes:
            cls_id = int(box.cls[0])
            conf = float(box.conf[0])
            name = model.names[cls_id]

            print(f"- {name}: {conf:.3f}")

    # Hiển thị ảnh kết quả
    result_image = result.plot()
    display(Image.fromarray(result_image[..., ::-1]))

from ultralytics import YOLO
from google.colab import files
from IPython.display import display
from PIL import Image

# Load mô hình đã train
model = YOLO("/content/runs/yolo12n_week3/train-2/weights/best.pt")

# Tải ảnh test
uploaded = files.upload()

for image_path in uploaded.keys():

    print("\n==============================")
    print("Ảnh:", image_path)

    # Hạ confidence xuống 0.05 để xem mô hình có dự đoán yếu hay không
    results = model.predict(
        source=image_path,
        conf=0.05,
        save=True
    )

    result = results[0]

    # In các đối tượng mô hình dự đoán
    if len(result.boxes) == 0:
        print("Không có dự đoán nào ngay cả ở conf = 0.05")
    else:
        print("Các dự đoán:")

        for box in result.boxes:
            cls_id = int(box.cls[0])
            conf = float(box.conf[0])
            name = model.names[cls_id]

            print(f"- {name}: {conf:.3f}")

    # Hiển thị ảnh kết quả
    result_image = result.plot()
    display(Image.fromarray(result_image[..., ::-1]))

from ultralytics import YOLO
from google.colab import files
from IPython.display import display
from PIL import Image

# Load mô hình đã train
model = YOLO("/content/runs/yolo12n_week3/train-2/weights/best.pt")

# Tải ảnh test
uploaded = files.upload()

for image_path in uploaded.keys():

    print("\n==============================")
    print("Ảnh:", image_path)

    # Hạ confidence xuống 0.05 để xem mô hình có dự đoán yếu hay không
    results = model.predict(
        source=image_path,
        conf=0.05,
        save=True
    )

    result = results[0]

    # In các đối tượng mô hình dự đoán
    if len(result.boxes) == 0:
        print("Không có dự đoán nào ngay cả ở conf = 0.05")
    else:
        print("Các dự đoán:")

        for box in result.boxes:
            cls_id = int(box.cls[0])
            conf = float(box.conf[0])
            name = model.names[cls_id]

            print(f"- {name}: {conf:.3f}")

    # Hiển thị ảnh kết quả
    result_image = result.plot()
    display(Image.fromarray(result_image[..., ::-1]))

from ultralytics import YOLO
from google.colab import files
from IPython.display import display
from PIL import Image

# Load mô hình đã train
model = YOLO("/content/runs/yolo12n_week3/train-2/weights/best.pt")

# Tải ảnh test
uploaded = files.upload()

for image_path in uploaded.keys():

    print("\n==============================")
    print("Ảnh:", image_path)

    # Hạ confidence xuống 0.05 để xem mô hình có dự đoán yếu hay không
    results = model.predict(
        source=image_path,
        conf=0.05,
        save=True
    )

    result = results[0]

    # In các đối tượng mô hình dự đoán
    if len(result.boxes) == 0:
        print("Không có dự đoán nào ngay cả ở conf = 0.05")
    else:
        print("Các dự đoán:")

        for box in result.boxes:
            cls_id = int(box.cls[0])
            conf = float(box.conf[0])
            name = model.names[cls_id]

            print(f"- {name}: {conf:.3f}")

    # Hiển thị ảnh kết quả
    result_image = result.plot()
    display(Image.fromarray(result_image[..., ::-1]))

from ultralytics import YOLO
from google.colab import files
from IPython.display import display
from PIL import Image

# Load mô hình đã train
model = YOLO("/content/runs/yolo12n_week3/train-2/weights/best.pt")

# Tải ảnh test
uploaded = files.upload()

for image_path in uploaded.keys():

    print("\n==============================")
    print("Ảnh:", image_path)

    # Hạ confidence xuống 0.05 để xem mô hình có dự đoán yếu hay không
    results = model.predict(
        source=image_path,
        conf=0.05,
        save=True
    )

    result = results[0]

    # In các đối tượng mô hình dự đoán
    if len(result.boxes) == 0:
        print("Không có dự đoán nào ngay cả ở conf = 0.05")
    else:
        print("Các dự đoán:")

        for box in result.boxes:
            cls_id = int(box.cls[0])
            conf = float(box.conf[0])
            name = model.names[cls_id]

            print(f"- {name}: {conf:.3f}")

    # Hiển thị ảnh kết quả
    result_image = result.plot()
    display(Image.fromarray(result_image[..., ::-1]))

from ultralytics import YOLO
from google.colab import files
from IPython.display import display
from PIL import Image

# Load mô hình đã train
model = YOLO("/content/runs/yolo12n_week3/train-2/weights/best.pt")

# Tải ảnh test
uploaded = files.upload()

for image_path in uploaded.keys():

    print("\n==============================")
    print("Ảnh:", image_path)

    # Hạ confidence xuống 0.05 để xem mô hình có dự đoán yếu hay không
    results = model.predict(
        source=image_path,
        conf=0.05,
        save=True
    )

    result = results[0]

    # In các đối tượng mô hình dự đoán
    if len(result.boxes) == 0:
        print("Không có dự đoán nào ngay cả ở conf = 0.05")
    else:
        print("Các dự đoán:")

        for box in result.boxes:
            cls_id = int(box.cls[0])
            conf = float(box.conf[0])
            name = model.names[cls_id]

            print(f"- {name}: {conf:.3f}")

    # Hiển thị ảnh kết quả
    result_image = result.plot()
    display(Image.fromarray(result_image[..., ::-1]))